### ISSUE TITLE
Android: google logo disappeared using mapPadding

### ISSUE THREAD

**Issue by ilhamyputra** [peterjuras/react-native-maps-map-padding-example#1]
Hi, I tried to build and run your example in Android but somehow cause google logo disappeared. When I removed mapPadding, it shows as usual.

Thanks.

**Comment by peterjuras** [comment]
Hi!

This example was only used to demonstrate a PR for react-native-maps to add the mapPadding property: https://github.com/react-community/react-native-maps/pull/1750

There are some comments in this PR that mention the dissapearing Google logo. Let me know if their suggestions help you to fix the problem.
